In [3]:
In this chapter, we shall cover the following topics:
‹ The linalg package
‹ The fft package
‹ Random numbers
‹ Continuous and discrete distributions

SyntaxError: invalid syntax (<ipython-input-3-01506efa4ecc>, line 1)

In [ ]:
the numpy contains the numpy.linalg.this helps for the computation like the eigen values,determinants ,solving linear equations
inverting matrices

In [ ]:
import numpy as np

In [4]:
X=np.mat('1 2 3;4 5 6;8 9 10')
X


matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [5]:
inverse=np.linalg.inv(X)

LinAlgError: Singular matrix

In [ ]:
#to check y the result is true or not 
multiply a and a inverse result to a identity matrix

In [ ]:
linear equatins  Ax=b

In [ ]:
the linear equations can be solved using the linalg.solve()

In [ ]:
# example
A = np.mat("1 -2 1;0 2 -8;-4 5 9")#A
b=np.array([0,8,-9])
solution=np.linalg.solve(A,b)
print(solution)

In [6]:
#to check s
np.dot(A,solution)

NameError: name 'A' is not defined

In [ ]:
finding eigen values and eigen vectors.the eigvals are used to calculate the eigen values in the AX=ax

In [ ]:
the eigen values are the scalar solution to the the matrices


In [10]:
B=np.mat('-3 -2;1 0')
B

matrix([[-3, -2],
        [ 1,  0]])

In [11]:
eigenvalue=np.linalg.eigvals(B)#only gives the eigen value tha is a scalar that is used to transform the orihinal matrix
eigenvalue

array([-2., -1.])

In [13]:
eigenvalues,eigenvector=np.linalg.eig(B)#gives both the eigen values and the eigen vectorss
print('eigenvalues:',eigenvalues)
print('eigenvectors:',eigenvector)

eigenvalues: [-2. -1.]
eigenvectors: [[-0.89442719  0.70710678]
 [ 0.4472136  -0.70710678]]


In [15]:
#to check whether the value is correct or not
c=np.dot(B,eigenvector)
print(c)

[[ 1.78885438 -0.70710678]
 [-0.89442719  0.70710678]]


In [18]:
x=np.dot(eigenvalues,eigenvector)
x

matrix([[ 1.34164079, -0.70710678]])

In [19]:
B[:,1]

matrix([[-2],
        [ 0]])

In [ ]:
for i in range(len(eigenvalues)):
    print