In [1]:
import numpy as np


In [2]:
a=np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
b=np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
b[0]#access all the elements in the first floor


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
b[0,0,:]#first floor 1 row all rooms

array([0, 1, 2, 3])

In [11]:
b[:,0,:]#despite the floor number give the 1 row all floors

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [ ]:
b[0,:,3]#give first floor ,all rows (indicated by:),last column

In [15]:
b.transpose()#transpose matrix

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [17]:
b.ravel()#flattens the matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
b.size

24

In [23]:
type(b)

numpy.ndarray

In [26]:
b.dtype

dtype('int32')

In [28]:
b.resize(6,4)#resizes the matrix in 6,4,(6 rows ,and 4 columns)

In [29]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])