In [2]:
import numpy as np


In [3]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
b=a*2
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [7]:
x=np.hstack((a,b#horizontaltly stacks the array
x

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [8]:
y=np.dstack((a,b))
y

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [10]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [13]:
a=np.arange(2)
b=a*2
np.column_stack((a,b))#stacks columns for 1d array

array([[0, 0],
       [1, 2]])

In [14]:
a=np.arange(2)
b=a*2
np.column_stack((a,b))#stacks rows for 1d array

array([[0, 0],
       [1, 2]])

splittng of array

In [24]:
d=np.arange(9).reshape((3,3))
np.hsplit(d,3)


[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [28]:
np.vsplit(d,3)#take each element of the column from each columns of matrix and form a single array by them.

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [26]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.split(d,3)#each row of the matri into aseprate array

In [30]:
d.ndim

2

In [32]:
d.dtype

dtype('int32')

In [33]:
type(d)

numpy.ndarray

In [34]:
d.itemsize

4

In [36]:
d.size#total elements

9